name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

#     steps:
#       - name: Run tests
#         run: mvn test

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
#       - name: Run the Maven verify phase
#         run: mvn --batch-mode --update-snapshots verify
      - name: Run tests
        run: mvn test
